redirects = [
  {from = "/webcam.html", to = "/webcam/"},
  {from = "/webcam.php", to = "/webcam/"},
  {from = "/booking/admin.php", to = "/"},
  {from = "/store.html", to = "/"},
  {from = "/aboutbv.php", to = "/about-bear-valley/"},
  {from = "/classifieds.php", to = "/"},
  {from = "/garage-sale", to = "/"},
  {from = "/classifieds", to = "/"},
  {from = "/green.php", to = "/"},
  {from = "/contact.php", to = "/contact/"},
  {from = "/reservations", to = "/rentals/"},
  {from = "/safety.php", to = "/safety-tips/"},
  {from = "/service.php", to = "/"},
  {from = "/snowmobilesales.php", to = "/"},
  {from = "/swnomobiles-with-mountains-in-background/", to = "/"},
  {from = "/enter-for-your-chance-to-win-by-the-16th/", to = "/"},
  {from = "/chasing-sled/", to = "/"},
  {from = "/enter-for-your-chance-to-win-by-the-16th/", to = "/"},
  {from = "/chasing-sled/", to = "/"},
  {from = "/poker-run-2/", to = "/"},
  {from = "/the-family-that-plays-together-stays-together/", to = "/"},
  {from = "/rentals.php", to = "/rentals/"},
{from = "/blog/", to = "/"},
{from = "/rentals.html", to = "/rentals/"},
{from = "/charity/", to = "/"},
{from = "/plugins.php", to = "/"},
{from = "/index.php", to = "/"},
{from = "/we-are-open-121115/", to = "/"},
{from = "/happy-new-year-2016/", to = "/"},
{from = "/family-picture/", to = "/"},
{from = "/1675/", to = "/"},
{from = "/689/", to = "/"},
{from = "/files/GTLE.pdf", to = "/"},
{from = "/taxi-service/", to = "/"},
{from = "/files/EN_SKANDICTUNDRA550F_10.pdf", to = "/"},
{from = "/files/EN_GrandTouringSPORT550F_10.pdf", to = "/"},
{from = "/1672/", to = "/"},
{from = "/safety.html", to = "/"},
{from = "/vip-service/", to = "/"},
{from = "/photo_gallery.php", to = "/"},
{from = "/call-us-for-your-20-taxi-ride/", to = "/"},
{from = "/charity.html", to = "/"},
{from = "/congrats-sandy-rappaport/", to = "/"},
{from = "/closing-our-last-trail-for-now-21615/", to = "/"},
{from = "/snowmobiling-in-a-blizzard/", to = "/"},
{from = "/vip-100-referral-program-press-release-2514/", to = "/"},
{from = "/alpine-trail-update-1515/", to = "/"},
{from = "/darn-asphalt-is-starting-to-show-11514/", to = "/"},
{from = "/deadline-to-order-2015-ski-doos-is-coming-32414/", to = "/"},
{from = "/sled-wars-snowmobiling-on-grass/", to = "/"},
{from = "/we-have-moved-next-to-the-lodge/", to = "/"},
{from = "/bear-valley-trail-closing-today-12115/", to = "/"},
{from = "/bear-valley-snowmobile-in-the-news/", to = "/"},
{from = "/weird-beard-1814/", to = "/"},
{from = "/little-bit-of-snow-but-not-enough-2114/", to = "/"},
{from = "/groomed-trails-are-great-but-watch-off-trail/", to = "/"},
{from = "/rim-fire-smoke-in-bear-valley/", to = "/"},
{from = "/economic-impact-of-snowmobiling-outperforms-economy/", to = "/"},
{from = "/bear-valley-snowmobile-is-in-the-news/", to = "/"},
{from = "/snow-is-holding-2-4-base-on-alpine-031014/", to = "/"},
{from = "/congrats-katie-and-jeremy-92510/", to = "/"},
{from = "/snow-is-coming-down/", to = "/"},
{from = "/lake-alpine-trail-has-fresh-snow-2915/", to = "/"},
{from = "/as-we-wait-for-the-next-storm-2615/", to = "/"},
{from = "/contact.html", to = "/contact/"},
{from = "/burn-kids-playing-in-the-snow/", to = "/"},
{from = "/2000-raised-for-search-and-rescue-ems/", to = "/"},
{from = "/alpine-trail-cruise-2/", to = "/"},
{from = "/help-transform-bear-valley/", to = "/"},
{from = "/alpine-trail-closed-again-122013/", to = "/"},
{from = "/greg-sandy-at-alpine/", to = "/"},
{from = "/snowy-vista-sunny-day/", to = "/"},
{from = "/vote-for-2015-cover-pic-for-calaveras-visitors-guide-111514/", to = "/"},
{from = "/having-fun-in-town-1415/", to = "/"},
{from = "/first-few-inches-of-fun-halloween-frost/", to = "/"},
{from = "/white-thanksgiving-11915/", to = "/"},
{from = "/snow-goddess/", to = "/"},
{from = "/snowy-cabin-by-highlands/", to = "/"},
{from = "/bear-valley-snowmobile-in-the-news-3114/", to = "/"},
{from = "/lake-alpine-trail-open-and-running-11015/", to = "/"},
{from = "/alpine-trail-opening-saturday-121413/", to = "/"},
{from = "/2014-models-being-delivered-today-121513/", to = "/"},
{from = "/poker-run-sat-29-support-search-rescue/", to = "/"},
{from = "/brp-produces-3-millionth-ski-doo-sled/", to = "/"},
{from = "/presidents-day-weekend-21315/", to = "/"},
{from = "/trail-update-jan-2014/", to = "/"},
{from = "/digging-out-a-car-after-a-3-foot-drop/", to = "/"},
{from = "/support-your-local-youth-trap-team-112514/", to = "/"},
{from = "/alpine-trail-cruise/", to = "/"},
{from = "/thanksgiving-weekend-12114/", to = "/"},
{from = "/bear-valley-cabin-with-a-view/", to = "/"},
{from = "/dont-forget-your-chains-in-snow-country/", to = "/"},
{from = "/our-shop-inside-the-lodge/", to = "/"},
{from = "/blue-sky-update-1915/", to = "/"},
{from = "/usfs-open-house-next-week-for-osv-draft-review-3715/", to = "/"},
{from = "/remember-your-parking-brake/", to = "/"},
{from = "/usfs-over-snow-use-meeting-notice-for-12516-in-sonora/", to = "/"},
{from = "/us-forest-service-open-house-on-stainislaus-nepa-study/", to = "/"},
{from = "/usfs-and-blue-ribbon-on-the-trails-22115/", to = "/"},
{from = "/bear-valley-snowmobile-in-the-news-vip-service/", to = "/"},
{from = "/alpine-and-bear-valley-trail-open-for-rentals-121714/", to = "/"},
{from = "/snow-or-shine-the-ride-goes-on/", to = "/"},
{from = "/time-for-service-112014/", to = "/"},
{from = "/cruising-the-alpine-trail-by-melodye-and-family-1315/", to = "/"},
{from = "/time-for-christmas-121614/", to = "/"},
{from = "/1670/", to = "/"},
{from = "/little-bit-of-snow-22815/", to = "/"},
{from = "/working-up-the-pole-121214/", to = "/"},
{from = "/happy-new-year-1115/", to = "/"},
{from = "/708/", to = "/"},
{from = "/bear-valley-ski-resort-opens-112815/", to = "/"},
{from = "/conveniently-located-in-the-bear-valley-lodge/", to = "/"},
{from = "/carving-through-bear-valley-via-snowmobile/", to = "/"},
{from = "/almost-got-some-snow-112314/", to = "/"},
{from = "/ski-doo-demo-day-in-yuba-pass-1913-11313/", to = "/"},
{from = "/its-white-just-not-thick-enough-12814/", to = "/"},
{from = "/enter-for-your-chance-to-win-by-the-16th/", to = "/"},
{from = "/lunch-at-highlands-on-the-lake-alpine-trail-1515/", to = "/"},
{from = "/its-raining-its-snowing-12414/", to = "/"},
{from = "/a-couple-having-fun-with-snowmobiles/", to = "/"},
{from = "/all-weather-hwy-4/", to = "/"},
{from = "/spicer-by-jensen/", to = "/"},
{from = "/snowy-white-scene/", to = "/"},
{from = "/snowy-mountain-storm/", to = "/"},
{from = "/sandy-and-greg-in-blue-suits/", to = "/"},
{from = "/snowy-and-icy-bear-lake/", to = "/"},
{from = "/fireworks-mlk-weekend-mark-your-calendar-11014/", to = "/"},
{from = "/new-parking-area-at-alpine-sno-park-103015/", to = "/"},
{from = "/red-and-yellow-snowmobiles/", to = "/"},
{from = "/mosquito-lake/", to = "/"},
{from = "/happy-puppies-playing-in-the-snow/", to = "/"},
{from = "/couple-on-snowmobile-with-orange-jacket/", to = "/"},
{from = "/stanislaus-meadow/", to = "/"},
{from = "/poker-run-participants/", to = "/"},
{from = "/files/EN_SUMMITX800_10_v3.pdf", to = "/"},
{from = "/swnomobiles-with-mountains-in-background/", to = "/"},
{from = "/rush-hour-in-bear-valley/", to = "/"},
{from = "/family-snowmobiling/", to = "/"},
{from = "/catching-air-with-a-snowmobile/", to = "/"},
{from = "/cruising-price-family/", to = "/"},
{from = "/greg-standing-on-snowmobile/", to = "/"},
{from = "/mp-and-tuff/", to = "/"},
{from = "/new-years-eve-snowmobiling-with-bear-valley-snowmobile/", to = "/"},
{from = "/playtime/", to = "/"},
{from = "/reservation-success/", to = "/"},
{from = "/chasing-sled/", to = "/"},
{from = "/poker-run-2/", to = "/"},
{from = "/sunset-in-bear-valley/", to = "/"},
{from = "/the-family-that-plays-together-stays-together/", to = "/"},
{from = "/snowmobile-with-child-carrier/", to = "/"},
{from = "/files/EN_SUMMITEVEREST600_10_v4.pdf", to = "/"},
{from = "/files/Bear_Valley_Village_Map.pdf", to = "/"},
{from = "/big-sandwich-after-snowmobiling/", to = "/"},
{from = "/files/EN_SUMMITX-RSHILLCLIMBEDITION_10_v4.pdf", to = "/"},
{from = "/files/SKANDICSWT.pdf", to = "/"},
{from = "/ski-doo-sales/", to = "/"},
{from = "/index.html", to = "/"},
{from = "/author/sandy/", to = "/"},
{from = "/classifieds/", to = "/"},
{from = "/snowmobilesales.html", to = "/"},
{from = "/author/adriamooney/", to = "/"},
{from = "/garage-sale/1040/", to = "/"},
{from = "/green.html", to = "/"},
{from = "/files/CMS.pdf", to = "/"},
{from = "/garage-sale/ski-doo-summit-700/", to = "/"},
{from = "/garage-sale/equinox-snow-coach-mvp/", to = "/"},
{from = "/wordpress_bvs/wp-content/uploads/2013/10/CMS.pdf", to = "/"},
{from = "/service.html", to = "/"},
{from = "/ski-doo-service/", to = "/"},
{from = "/files/Summit_X.pdf", to = "/"},
{from = "/garage-sale/yamaha-mountain-max/", to = "/"},
{from = "/garage-sale/touring-sle/", to = "/"},
{from = "/files/RMS.pdf", to = "/"},
{from = "/garage-sale/ski-doo-800-x/", to = "/"},
{from = "/files/EN_SKANDICTUNDRASPORT550F_10.pdf", to = "/"},
{from = "/blog/page/6/", to = "/"},
{from = "/category/uncategorized/", to = "/"},
{from = "/garage-sale/quad-plow-from-yamaha-450-kodiak/", to = "/"},
{from = "/wordpress_bvs/wp-content/uploads/2015/12/2015-VIP-SERVICE-QUESTIONAIRE-no-year-on-form.pdf", to = "/"},
{from = "/blog/page/3/", to = "/"},
{from = "/garage-sale/arctic-cat-power-extreme/", to = "/"},
{from = "/garage-sale/low-mileage-2011-skidoo-summit-800r-p-tek-154/", to = "/"},
{from = "/category/news/", to = "/"},
{from = "/blog/page/5/", to = "/"},
{from = "/blog/page/7/", to = "/"},
{from = "/garage-sale/2004-ski-doo-gsx-500-ss/", to = "/"},
{from = "/blog/page/4/", to = "/"},
{from = "/wordpress_bvs/wp-content/uploads/2014/11/VIP_SERVICE_QUESTIONAIRE.pdf", to = "/"},
{from = "/atom.xml", to = "/"},
{from = "/testing_grounds/files/RMS.pdf", to = "/"},
{from = "/rentals/event-booking-nojs.php?date=2014-01-21", to = "/"},
{from = "/testing_grounds/files/LMS.pdf", to = "/"},
{from = "/robots.txt", to = "/"},
{from = "/rentals/event-booking-nojs.php?date=2014-02-02", to = "/"},
{from = "/mobile-booking-page/", to = "/"},
{from = "/wordpress_bvs/xmlrpc.php", to = "/"},
{from = "/alpine-trail-is-booked-122914/", to = "/"},
{from = "/got-chains-122014/", to = "/"},
{from = "/press-page.php", to = "/"},
{from = "/http:/www.bvsnowmobile.com/", to = "/"}
  ]